import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Navbar } from "../../components/shared";
import { apiConnector } from "../../integrations/ApiConnector";
import { aiEndpoints, campaignEndpoints, clubEndpoints } from "../../integrations/ApiEndpoints";
import { FaMagic, FaSpinner, FaCheck } from "react-icons/fa";
import { showSuccessToast, showErrorToast } from "../../utils/Toasts";
import "./CreateCampaign.scss";

const CreateCampaign = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    title: "",
    category: "Education",
    goal: "",
    description: "",
    keyPoints: ""
  });
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [clubId, setClubId] = useState(null);

  useEffect(() => {
    // Fetch a club ID to use for the campaign
    const fetchClub = async () => {
      try {
        const response = await apiConnector("GET", clubEndpoints.all);
        if (response.data && response.data.length > 0) {
          // Just pick the first club for demo purposes
          setClubId(response.data[0]._id);
        }
      } catch (error) {
        console.error("Failed to fetch clubs", error);
      }
    };
    fetchClub();
  }, []);

  const categories = [
    "Education",
    "Healthcare",
    "Environment",
    "Disaster Relief",
    "Community Development",
    "Animal Welfare",
    "Other"
  ];

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleMagicWrite = async () => {
    if (!formData.title) {
      showErrorToast("Please enter a campaign title first!");
      return;
    }

    setIsGenerating(true);
    try {
      const response = await apiConnector("POST", aiEndpoints.generateDescription, {
        title: formData.title,
        category: formData.category,
        keyPoints: formData.keyPoints
      });

      if (response.data && response.data.description) {
        setFormData(prev => ({ ...prev, description: response.data.description }));
        showSuccessToast("Description generated by AI!");
      }
    } catch (error) {
      console.error("AI Generation Error:", error);
      showErrorToast("Failed to generate description. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!clubId) {
      showErrorToast("System Error: No active NGO account found.");
      return;
    }

    setIsSubmitting(true);
    
    try {
      const slug = formData.title.toLowerCase().replace(/ /g, "-") + "-" + Date.now();
      
      const payload = {
        title: formData.title,
        slug: slug,
        description: formData.description,
        clubId: clubId,
        category: formData.category,
        goalAmount: Number(formData.goal),
        startDate: new Date(),
        endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days from now
        beneficiaries: "General Public",
        images: [{ url: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80", caption: "Campaign Cover" }] // Default image
      };

      const response = await apiConnector("POST", campaignEndpoints.create, payload);
      
      if (response.data.success) {
        showSuccessToast("Campaign launched successfully!");
        setTimeout(() => {
          navigate("/trending");
        }, 1500);
      }
    } catch (error) {
      console.error("Campaign Creation Error:", error);
      showErrorToast(error.response?.data?.error || "Failed to create campaign");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <>
      <Navbar />
      <div className="create-campaign-container">
        <div className="form-wrapper">
          <div className="header">
            <h1>Start a New Campaign</h1>
            <p>Create a compelling fundraiser in seconds with AI assistance.</p>
          </div>

          <form onSubmit={handleSubmit}>
            <div className="form-group">
              <label>Campaign Title</label>
              <input
                type="text"
                name="title"
                value={formData.title}
                onChange={handleChange}
                placeholder="e.g., Clean Water for Village X"
                required
              />
            </div>

            <div className="form-row">
              <div className="form-group">
                <label>Category</label>
                <select name="category" value={formData.category} onChange={handleChange}>
                  {categories.map(cat => (
                    <option key={cat} value={cat}>{cat}</option>
                  ))}
                </select>
              </div>

              <div className="form-group">
                <label>Fundraising Goal (₹)</label>
                <input
                  type="number"
                  name="goal"
                  value={formData.goal}
                  onChange={handleChange}
                  placeholder="5000"
                  required
                />
              </div>
            </div>

            <div className="ai-section">
              <div className="form-group">
                <label>Key Points (Optional)</label>
                <input
                  type="text"
                  name="keyPoints"
                  value={formData.keyPoints}
                  onChange={handleChange}
                  placeholder="e.g., urgent need, affects 500 kids, tax deductible"
                />
                <small>Add a few keywords to guide the AI.</small>
              </div>

              <button 
                type="button" 
                className={`magic-btn ${isGenerating ? 'loading' : ''}`}
                onClick={handleMagicWrite}
                disabled={isGenerating}
              >
                {isGenerating ? <FaSpinner className="spin" /> : <FaMagic />}
                {isGenerating ? "Writing..." : "Magic Write Description"}
              </button>
            </div>

            <div className="form-group">
              <label>Description</label>
              <textarea
                name="description"
                value={formData.description}
                onChange={handleChange}
                rows="10"
                placeholder="Describe your campaign in detail..."
                required
              ></textarea>
            </div>

            <button type="submit" className="submit-btn" disabled={isSubmitting}>
              {isSubmitting ? "Creating..." : "Launch Campaign"}
            </button>
          </form>
        </div>
      </div>
    </>
  );
};

export default CreateCampaign;
